sonar.projectKey=patorsiang_portfolio-platform-2026
sonar.projectName=Patorsiang Portfolio Platform 2026
sonar.organization=patorsiang

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/dist/**,**/build/**,**/coverage/**,legacy-v1/**
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*,legacy-v1/**

sonar.sourceEncoding=UTF-8

