/**
 * Downloads every remote image referenced by a post into public/posts/<slug>/
 * and writes the URL-to-path map the renderer uses.
 *
 * Run by hand when a post gains an image:
 *   bun run --cwd apps/portfolio-web vendor:post-images
 *
 * Not in CI, and not at request time: ISR runs on a read-only filesystem and
 * cannot write to public/. Between deploys an unvendored image renders as a
 * link, which is why the renderer degrades rather than emitting a broken img.
 *
 * These images are event photography by other people. Each keeps its source
 * URL in sources.json so attribution stays recoverable.
 *
 * Uses `fetchRawPosts`, not `fetchPosts`: `fetchPosts` returns `body` already
 * rendered to HTML by `renderPostBody`, and `selectImageUrls` expects
 * markdown link syntax (`![alt](url)`), which no longer exists once an image
 * has become an `<img>` (or, unvendored, an `<a>`) tag. `fetchRawPosts`
 * returns the pre-render markdown body instead.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { fetchRawPosts, selectImageUrls } from "@patorsiang/content";

const publicDir = join(import.meta.dir, "../public/posts");
const mapPath = join(import.meta.dir, "../src/lib/vendored-images.ts");

const extensionOf = (url: string) => {
  const path = new URL(url).pathname;
  const match = /\.(png|jpe?g|webp|gif|svg)$/i.exec(path);

  // Cloudinary and similar serve extensionless transform URLs; webp is the
  // safe default and the browser sniffs the real type anyway.
  return match ? match[1].toLowerCase() : "webp";
};

async function main() {
  // Raw markdown, not rendered HTML: selectImageUrls reads markdown syntax.
  const posts = await fetchRawPosts();
  const entries: [string, string][] = [];

  for (const post of posts) {
    const urls = selectImageUrls(post.body);
    if (urls.length === 0) continue;

    const dir = join(publicDir, post.slug);
    mkdirSync(dir, { recursive: true });

    const sources: Record<string, string> = {};

    for (const [index, url] of urls.entries()) {
      const name = `image-${index + 1}.${extensionOf(url)}`;
      const response = await fetch(url);

      if (!response.ok) {
        console.warn(`skipped ${url}: ${response.status}`);
        continue;
      }

      writeFileSync(join(dir, name), Buffer.from(await response.arrayBuffer()));
      sources[name] = url;
      entries.push([url, `/posts/${post.slug}/${name}`]);
      console.log(`vendored ${url} -> /posts/${post.slug}/${name}`);
    }

    writeFileSync(join(dir, "sources.json"), `${JSON.stringify(sources, null, 2)}\n`, "utf8");
  }

  const literal = entries
    .map(([url, path]) => `  [${JSON.stringify(url)}, ${JSON.stringify(path)}],`)
    .join("\n");

  writeFileSync(
    mapPath,
    `/* Generated by scripts/vendor-post-images.ts. Do not edit by hand. */\n` +
      `export const VENDORED_IMAGES: ReadonlyMap<string, string> = new Map([\n${literal}\n]);\n`,
    "utf8",
  );

  console.log(`wrote ${mapPath}`);
}

await main();
