/* Generated by scripts/vendor-post-images.ts. Do not edit by hand. */
export const VENDORED_IMAGES: ReadonlyMap<string, string> = new Map([
  [
    "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_1080,q_100,w_1080/v1/gcs/platform-data-goog/events/blob_o3IC4RX",
    "/posts/gdg-buildwithai-2026/image-1.png",
  ],
]);
