/**
 * Generated by scripts/vendor-post-images.ts. Do not edit by hand.
 *
 * Empty because thinking-in-public's front-matter commit (this branch's
 * Task 5) has not been pushed yet — fetchPosts() throws against the live
 * repo until it is. Once the user reviews and pushes that commit, run
 * `bun run vendor:post-images` to populate this for real.
 */
export const VENDORED_IMAGES: ReadonlyMap<string, string> = new Map([]);
